envs:
  - name: ScannetTool
    data_source: ae
    seed: [0, 3419, 1]
    n_envs: 3419
    max_turns: 10
    response_length_per_turn: 512
    config:
      jsonl_path: ${oc.env:HOME}/projects/viewsuite/data/viewsuite_5k/active_explore_train_filter.jsonl
      image_size: [512, 512]
      eval_mode: true
      use_example_in_sys_prompt: false
      client_url_file_path: ${oc.env:HOME}/projects/viewsuite/client_url.txt
      render_backend: client
      max_turns: 10
      per_turn_format_reward: 0.01
      format_reward: 0.0
      give_answer_reward: 0.1
      action_only_mode: true
