envs:
  - name: MindCubeNoToolGym
    data_source: mindcube
    seed: [0,10000,1]
    n_envs: 10000
    max_turns: 1
    response_length_per_turn: 2048
    config:
      data_path: ${oc.env:HOME}/projects/viewsuite/data/mindcube
      split: train
      image_size: [512,512]
      format: eval_mode
      format_reward: 0.2
      answer_reward: 0.8
